# Generated by Django 4.2.6 on 2023-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userprofile_address_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='block',
            field=models.ManyToManyField(related_name='blocked', to='social.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='social.userprofile'),
        ),
    ]
